[theme]
primaryColor = "#c41e3a"
backgroundColor = "#D3D3D3"
secondaryBackgroundColor = "#f0ebe3"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
