[theme]
primaryColor = "#c41e3a"
backgroundColor = "#E8E8E8"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
